version: '3.9'

services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser-new
    restart: unless-stopped
    networks:
      - net
    volumes:
      - ./files:/files
      - ./config/.filebrowser.json:/.filebrowser.json
    ports:
      - 8088:80
    # logging:
    #   driver: 'none'

networks:
  net: