version: '3.9'

services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: fbrowser
    restart: unless-stopped
    networks:
      - net
    healthcheck:
      disable: true      
    volumes:
    # data
      - ./files:/files
    # config
      - ./config/.filebrowser.json:/.filebrowser.json
    ports:
      - 4000:80
    entrypoint: ["/filebrowser","--database=/config/database.db","--disable-thumbnails","--disable-preview-resize","--disable-type-detection-by-header","--cache-dir","/tmp"]
    # logging:
    #   driver: 'none'

networks:
  net: