version: '3.9'

services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: fbrowser
    restart: unless-stopped
    networks:
      - net
    healthcheck:
      disable: true      
    ports:
      - 4000:80
    volumes:
      - ./config/.filebrowser.json:/.filebrowser.json
      - ./files:/files
      - public:/files
    entrypoint: ["/filebrowser","--database=/config/database.db","--disable-thumbnails","--disable-preview-resize","--disable-type-detection-by-header","--cache-dir","/tmp"]
    # logging:
    #   driver: 'none'

volumes:
  public:
    external: true

networks:
  net: