version: '3.9'

services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser-new
    restart: unless-stopped
    networks:
      - net
    healthcheck:
      disable: true      
    volumes:
    # data
      - ./files:/files
    # config
      ##########- ./config/database.db:/database/database.db
      - ./config/.filebrowser.json:/.filebrowser.json
    ports:
      - 8088:80
    entrypoint: ["/filebrowser","--disable-preview-resize","--disable-type-detection-by-header","--cache-dir","/tmp"]
    # logging:
    #   driver: 'none'

networks:
  net: