version: '3.9'

services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: fbrowser
    restart: unless-stopped
    networks:
      - net
    healthcheck:
      disable: true
    ports:
      - 4000:80
    volumes:
      - ./config/.filebrowser.json:/.filebrowser.json
      - 'D:\_POMINI\src\backend\mediaservice\public:/files'
      ###- '${USERPROFILE}/TEORESI/ASP-Pomini Spare Parts - General/GEMINI:/files'
      ### - public:/files
    entrypoint:
      [
        "/filebrowser",
        "--database=/config/database.db",
        "--disable-thumbnails",
        "--disable-preview-resize",
        "--disable-type-detection-by-header",
        "--cache-dir",
        "/tmp"
      ]

volumes:
  public:
    external: true

networks:
  net:
